# STEP 1 build executable binary
FROM golang:1.9 as builder

# Install git
# RUN apk update && apk add git 

# Copy source files and set proper work dir
COPY . $GOPATH/src/go-app/
WORKDIR $GOPATH/src/go-app/

#get dependancies
RUN go get -d -v

#disable crosscompiling
ENV CGO_ENABLED=0
#compile linux only
ENV GOOS=linux

#build the binary
RUN go build  -ldflags '-w -s' -a -installsuffix cgo -o reporter

# STEP 2 build a small image
# start from scratch
FROM scratch
# Copy our static executable
COPY --from=builder /go/src/go-app/reporter reporter
ENTRYPOINT [ "./reporter" ]
CMD [ "--help" ]
